In [ ]:
#create a Vector 
import numpy as np

vector  = np.array([2,4,6])

print(vector)


[2 4 6]


In [ ]:
#Create a Matrix
import numpy as np 

matrix = np.array([[1,2],[3,4]])
print(matrix)

[[1 2]
 [3 4]]


In [ ]:
#Matrix Addition

import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [ ]:
#Manual Gradient Descent 

#inital Weight
weight = 0.5
#Learning Rate
learning_rate = 0.1
#Gradient 
gradient= 2
#update weight 
weight = weight - learning_rate * gradient
print("Updated Weight:", weight)

Updated Weight: 0.3
