In [6]:
import numpy as np
arr = np.arange(6)

In [7]:
import numpy as np
my_arr = np.array([[1, 2], [3, 4], [5, 6],[7, 8]], dtype=np.uint16)
print("shape of array:", my_arr.shape)
print("number of dimensions:", my_arr.ndim)
print("The size of ach item in the array:", my_arr.itemsize, )

shape of array: (4, 2)
number of dimensions: 2
The size of ach item in the array: 2


In [8]:
import numpy as np
arr = np.ones((3, 3), dtype=np.bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
import numpy as np
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

In [10]:
import numpy as np
zeros_arr = np.zeros(5)
one_arr = np.ones(5)
print("Zeros", zeros_arr)
print("Ones", one_arr)

Zeros [0. 0. 0. 0. 0.]
Ones [1. 1. 1. 1. 1.]


In [11]:
import numpy as np
arr = np.linspace(5, 50, 10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [12]:
import numpy as np
py_list = [1, 2, 3, 4, 5]
arr = np.array(py_list)
print(arr)

[1 2 3 4 5]


In [13]:
import numpy as np
arr = np.arange(10)
print("Array:",arr)
print("Memory size in bytes:", arr.nbytes)

Array: [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes: 80


In [14]:
import numpy as np
arr = np.arange(10)
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)

Reversed Array: [9 8 7 6 5 4 3 2 1 0]


In [15]:
import numpy as np
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
import numpy as np
arr = np.arange(1, 17).reshape(4, 4)
print("Array:\n",arr)
first_row = arr[0,]
print("First row:", first_row)
last_column = arr[:, -1]
print("Last column:", last_column)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First row: [1 2 3 4]
Last column: [ 4  8 12 16]


In [17]:
import numpy as np
#original array
samplearray = np.array([[3, 6, 9, 12],
                       [15, 18, 21, 24],
                       [27, 30, 33, 36], 
                       [39, 42, 45, 48]])

#using slicing to select odd rows and even columns
#the slice [1::2] selects every second element starting from index 1 (odd rows)
#the slice [0::2] selects every second element starting from index 0 (even columns)
newArray = samplearray[1::2, 0::2]
print("Original array:")
print(samplearray)
print("\nNew array with odd rows and even columns:")
print(newArray)

Original array:
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]]

New array with odd rows and even columns:
[[15 21]
 [39 45]]


In [18]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_arr = np.hstack((a, b))
print("Stacked array:", stacked_arr)

Stacked array: [1 2 3 4 5 6]
